#!/bin/bash
set -a
[ -f .env ] && . .env

if [ ! -d ./src/frontend/node_modules ]; then
    mkdir ./src/frontend/node_modules
fi

docker build $1 -f Dockerfile_frontend -t hci/frontend:latest -t hci/frontend:production -t hci/frontend:production-`date +"%Y-%m-%d"` .
