version: '3.7'

services:
  frontend:
    image: hci/frontend:latest
    command: npm start
    volumes:
      - ./src/frontend/src:/usr/src/src
      - frontend:/usr/src/
      - ./src/frontend/public:/usr/src/public
      - front_node_modules:/usr/src/node_modules
    environment:
      - HOST=0.0.0.0
      - PORT=${FRONTEND_PORT}
      - CHOKIDAR_USEPOLLING=true
      - API_HOST=${BACKEND_RUNNING_ON}
      - API_PORT=${BACKEND_PORT}
  backend: &backend
    user: "container_user:container_user"
    image: hci/backend:latest
    tty: true
    stdin_open: true
    volumes:
      - ./src/backend:/opt/backend
    secrets:
      - sentry
      - postgres_db
      - postgres_usr
      - postgres_pswd
    env_file:
      - .env
    environment:
      - PYTHONPATH=/opt/backend
      - DJANGO_SETTINGS_MODULE=project.settings
      - FRONTEND_PORT=${FRONTEND_PORT}
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_USER_FILE=/run/secrets/postgres_usr
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_pswd
      - SENTRY_DSN_FILE=/run/secrets/sentry
  db:
    image: postgres:12.1
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - pgdata:/var/lib/postgresql/data/
    secrets:
      - postgres_db
      - postgres_usr
      - postgres_pswd
    environment:
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_USER_FILE=/run/secrets/postgres_usr
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_pswd
  rabbitmq:
    image: rabbitmq:3.8.2-alpine
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 1
  celery_worker:
    <<: *backend
    command: start_celery worker
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
    tty: false
    stdin_open: false
  celery_beat:
    <<: *backend
    command: start_celery beat
    deploy:
      restart_policy:
        condition: on-failure
    tty: false
    stdin_open: false
  nginx:
    image: nginx:1.17.6
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - 80:80
      - "443:443"
    volumes:
      - ./conf/nginx-proxy-dev.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src/backend:/opt/backend
      - ./ssl/concatenated.cer:/etc/ssl/concatenated.cer
      - ./ssl/private_key.key:/etc/ssl/private_key.key
volumes:
  pgdata:
  frontend:
    driver: local
    driver_opts:
      type: none
      device: $PWD/src/frontend/
      o: bind
  front_node_modules:
    driver: local
    driver_opts:
      type: none
      device: $PWD/src/frontend/node_modules
      o: bind

secrets:
  sentry:
    file: secrets/sentry.txt
  postgres_db:
    file: secrets/pst_db.txt
  postgres_usr:
    file: secrets/pst_usr.txt
  postgres_pswd:
    file: secrets/pst_pswd.txt
