version: '3'

services:
  backend: &backend
    user: "container_user:container_user"
    image: hci/backend:latest
    command: rungunicorn
    container_name: backend
    tty: true
    stdin_open: true
    depends_on:
      - rabbitmq
      - celery_worker
    expose: 
      - "8000"
    volumes:
      - ./src/backend:/opt/backend
    env_file:
      - .env
  rabbitmq:
    image: rabbitmq:3.8.2-alpine
    container_name: rabbitmq
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 1
  celery_worker:
    <<: *backend
    container_name: celery_worker
    command: celery -A project worker --loglevel=info --sentry=${SENTRY_DSN}
    ports: []
    tty: false
    stdin_open: false
    depends_on: 
      - rabbitmq
  celery_beat:
    <<: *backendrestart
    container_name: celery_beat
    command: celery -A project worker --loglevel=info --sentry=${SENTRY_DSN}
    ports: []
    tty: false
    stdin_open: false
    depends_on: 
      - rabbitmq
  nginx:
    image: hci/frontend:latest
    restart: always
    container_name: proxy_server
    ports:
      - 80:80
      - "443:443"
    volumes:
      - ./conf/nginx-proxy-prod.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src/backend:/opt/backend
      - ./ssl/concatenated.cer:/etc/ssl/concatenated.cer
      - ./ssl/private_key.key:/etc/ssl/private_key.key
    depends_on:
      - backend    
volumes:
  pgdata:
