#!/bin/bash
set -a
[ -f .env ] && . .env

# execute a command inside the running container
if [ $1 = "frontend" ]
then
    shift
    docker exec -ti $(docker container ls | grep frontend | xargs | awk '{print $NF}') ./entrypoint.sh ${@:1}
else
    shift
    docker exec -ti $(docker container ls | grep backend | xargs | awk '{print $NF}') ./entrypoint.sh ${@:1}
fi